
<%-- 
    Document   : [考勤计算]明细页
    Created on : 2018-03-28 15:47:59
    Author     : mansan
--%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <title>[考勤计算]明细</title>
        <%@include file="/commons/get.jsp" %>
    </head>
    <body>
        <rx:toolbar toolbarId="toolbar1"/>
        <div id="form1" class="form-outer">
             <div style="padding:5px;">
             	<table style="width:100%" class="table-detail" cellpadding="0" cellspacing="1">
                	<caption>[考勤计算]基本信息</caption>
					<tr>
						<th>考勤档案：</th>
						<td>
							${atsAttenceCalculate.fileId}
						</td>
					</tr>
					<tr>
						<th>考勤日期：</th>
						<td>
							${atsAttenceCalculate.attenceTime}
						</td>
					</tr>
					<tr>
						<th>是否排班：</th>
						<td>
							${atsAttenceCalculate.isScheduleShift}
						</td>
					</tr>
					<tr>
						<th>日期类型：</th>
						<td>
							${atsAttenceCalculate.dateType}
						</td>
					</tr>
					<tr>
						<th>假期名称：</th>
						<td>
							${atsAttenceCalculate.holidayName}
						</td>
					</tr>
					<tr>
						<th>是否有打卡记录：</th>
						<td>
							${atsAttenceCalculate.isCardRecord}
						</td>
					</tr>
					<tr>
						<th>考勤时间：</th>
						<td>
							${atsAttenceCalculate.shiftTime}
						</td>
					</tr>
					<tr>
						<th>应出勤时数：</th>
						<td>
							${atsAttenceCalculate.shouldAttenceHours}
						</td>
					</tr>
					<tr>
						<th>实际出勤时数：</th>
						<td>
							${atsAttenceCalculate.actualAttenceHours}
						</td>
					</tr>
					<tr>
						<th>有效打卡记录：</th>
						<td>
							${atsAttenceCalculate.cardRecord}
						</td>
					</tr>
					<tr>
						<th>旷工次数：</th>
						<td>
							${atsAttenceCalculate.absentNumber}
						</td>
					</tr>
					<tr>
						<th>旷工小时数：</th>
						<td>
							${atsAttenceCalculate.absentTime}
						</td>
					</tr>
					<tr>
						<th>旷工记录：</th>
						<td>
							${atsAttenceCalculate.absentRecord}
						</td>
					</tr>
					<tr>
						<th>迟到次数：</th>
						<td>
							${atsAttenceCalculate.lateNumber}
						</td>
					</tr>
					<tr>
						<th>迟到分钟数：</th>
						<td>
							${atsAttenceCalculate.lateTime}
						</td>
					</tr>
					<tr>
						<th>迟到记录：</th>
						<td>
							${atsAttenceCalculate.lateRecord}
						</td>
					</tr>
					<tr>
						<th>早退次数：</th>
						<td>
							${atsAttenceCalculate.leaveNumber}
						</td>
					</tr>
					<tr>
						<th>早退分钟数：</th>
						<td>
							${atsAttenceCalculate.leaveTime}
						</td>
					</tr>
					<tr>
						<th>早退记录：</th>
						<td>
							${atsAttenceCalculate.leaveRecord}
						</td>
					</tr>
					<tr>
						<th>加班次数：</th>
						<td>
							${atsAttenceCalculate.otNumber}
						</td>
					</tr>
					<tr>
						<th>加班分钟数：</th>
						<td>
							${atsAttenceCalculate.otTime}
						</td>
					</tr>
					<tr>
						<th>加班记录：</th>
						<td>
							${atsAttenceCalculate.otRecord}
						</td>
					</tr>
					<tr>
						<th>请假次数：</th>
						<td>
							${atsAttenceCalculate.holidayNumber}
						</td>
					</tr>
					<tr>
						<th>请假分钟数：</th>
						<td>
							${atsAttenceCalculate.holidayTime}
						</td>
					</tr>
					<tr>
						<th>请假时间单位：</th>
						<td>
							${atsAttenceCalculate.holidayUnit}
						</td>
					</tr>
					<tr>
						<th>请假记录：</th>
						<td>
							${atsAttenceCalculate.holidayRecord}
						</td>
					</tr>
					<tr>
						<th>出差次数：</th>
						<td>
							${atsAttenceCalculate.tripNumber}
						</td>
					</tr>
					<tr>
						<th>出差分钟数：</th>
						<td>
							${atsAttenceCalculate.tripTime}
						</td>
					</tr>
					<tr>
						<th>出差记录：</th>
						<td>
							${atsAttenceCalculate.tripRecord}
						</td>
					</tr>
					<tr>
						<th>有效打卡记录：</th>
						<td>
							${atsAttenceCalculate.validCardRecord}
						</td>
					</tr>
					<tr>
						<th>考勤类型：</th>
						<td>
							${atsAttenceCalculate.attenceType}
						</td>
					</tr>
					<tr>
						<th>班次：</th>
						<td>
							${atsAttenceCalculate.shiftId}
						</td>
					</tr>
					<tr>
						<th>ABNORMITY：</th>
						<td>
							${atsAttenceCalculate.abnormity}
						</td>
					</tr>
					<tr>
						<th>租用机构ID：</th>
						<td>
							${atsAttenceCalculate.tenantId}
						</td>
					</tr>
					<tr>
						<th>创建人ID：</th>
						<td>
							${atsAttenceCalculate.createBy}
						</td>
					</tr>
					<tr>
						<th>创建时间：</th>
						<td>
							${atsAttenceCalculate.createTime}
						</td>
					</tr>
					<tr>
						<th>更新人ID：</th>
						<td>
							${atsAttenceCalculate.updateBy}
						</td>
					</tr>
					<tr>
						<th>更新时间：</th>
						<td>
							${atsAttenceCalculate.updateTime}
						</td>
					</tr>
				</table>
             </div>
    	</div>
        <rx:detailScript baseUrl="oa/ats/atsAttenceCalculate" 
        entityName="com.redxun.oa.ats.entity.AtsAttenceCalculate"
        formId="form1"/>
        
        <script type="text/javascript">
		mini.parse();
		var form = new mini.Form("#form1");
		var pkId = '${atsAttenceCalculate.id}';
		$(function(){
			$.ajax({
				type:'POST',
				url:"${ctxPath}/oa/ats/atsAttenceCalculate/getJson.do",
				data:{ids:pkId},
				success:function (json) {
					form.setData(json);
				}					
			});
		})
		</script>
    </body>
</html>