CREATE TABLE BPM_MOBILE_FORM  (
   ID_                  VARCHAR2(50),
   VIEW_ID_             VARCHAR2(50),
   NAME_                VARCHAR2(50),
   ALIAS_               VARCHAR2(50),
   FORM_HTML            CLOB,
   TENANT_ID_           VARCHAR2(50),
   TREE_ID_             VARCHAR2(50),
   CREATE_BY_           VARCHAR2(50),
   CREATE_TIME_         DATE,
   UPDATE_BY_           VARCHAR2(50),
   UPDATE_TIME_         DATE
);

COMMENT ON TABLE BPM_MOBILE_FORM IS
'手机表单配置表';

COMMENT ON COLUMN BPM_MOBILE_FORM.ID_ IS
'主键';

COMMENT ON COLUMN BPM_MOBILE_FORM.VIEW_ID_ IS
'关联表单ID';

COMMENT ON COLUMN BPM_MOBILE_FORM.NAME_ IS
'名称';

COMMENT ON COLUMN BPM_MOBILE_FORM.ALIAS_ IS
'别名';

COMMENT ON COLUMN BPM_MOBILE_FORM.FORM_HTML IS
'表单模版';

COMMENT ON COLUMN BPM_MOBILE_FORM.TENANT_ID_ IS
'租户ID';

COMMENT ON COLUMN BPM_MOBILE_FORM.TREE_ID_ IS
'表单分类ID';

COMMENT ON COLUMN BPM_MOBILE_FORM.CREATE_BY_ IS
'创建人';

COMMENT ON COLUMN BPM_MOBILE_FORM.CREATE_TIME_ IS
'创建时间';

COMMENT ON COLUMN BPM_MOBILE_FORM.UPDATE_BY_ IS
'更新人';

COMMENT ON COLUMN BPM_MOBILE_FORM.UPDATE_TIME_ IS
'更新时间';



CREATE TABLE BPM_FORM_TEMPLATE  (
   ID_                  VARCHAR2(50)                    NOT NULL,
   NAME_                VARCHAR2(50),
   ALIAS_               VARCHAR2(50),
   TEMPLATE_            CLOB,
   TYPE_                VARCHAR2(50),
   INIT_                SMALLINT,
   TENANT_ID_           VARCHAR2(50),
   CREATE_BY_           VARCHAR2(50),
   CREATE_TIME_         DATE,
   UPDATE_BY_           VARCHAR2(50),
   UPDATE_TIME_         DATE,
   CATEGORY_            VARCHAR2(50),
   CONSTRAINT PK_BPM_FORM_TEMPLATE PRIMARY KEY (ID_)
);

COMMENT ON TABLE BPM_FORM_TEMPLATE IS
'表单模版';

COMMENT ON COLUMN BPM_FORM_TEMPLATE.ID_ IS
'主键';

COMMENT ON COLUMN BPM_FORM_TEMPLATE.NAME_ IS
'模版名称';

COMMENT ON COLUMN BPM_FORM_TEMPLATE.ALIAS_ IS
'别名';

COMMENT ON COLUMN BPM_FORM_TEMPLATE.TEMPLATE_ IS
'模版';

COMMENT ON COLUMN BPM_FORM_TEMPLATE.TYPE_ IS
'模版类型 (pc,mobile)';

COMMENT ON COLUMN BPM_FORM_TEMPLATE.INIT_ IS
'初始添加的(1是,0否)';

COMMENT ON COLUMN BPM_FORM_TEMPLATE.TENANT_ID_ IS
'租户ID';

COMMENT ON COLUMN BPM_FORM_TEMPLATE.CREATE_BY_ IS
'创建人';

COMMENT ON COLUMN BPM_FORM_TEMPLATE.CREATE_TIME_ IS
'创建时间';

COMMENT ON COLUMN BPM_FORM_TEMPLATE.UPDATE_BY_ IS
'更新人';

COMMENT ON COLUMN BPM_FORM_TEMPLATE.UPDATE_TIME_ IS
'更新时间';

COMMENT ON COLUMN BPM_FORM_TEMPLATE.CATEGORY_ IS
'类别';

alter table ACT_RU_TASK add ENABLE_MOBILE_ INT;

COMMENT ON COLUMN ACT_RU_TASK.ENABLE_MOBILE_ IS
'是否支持手机表单';


alter table bpm_node_jump add ENABLE_MOBILE_ INT;


COMMENT ON COLUMN bpm_node_jump.ENABLE_MOBILE_ IS
'是否支持手机表单';

alter table bpm_sol_fv add MOBILE_ALIAS_ varchar(50);
COMMENT ON COLUMN bpm_sol_fv.MOBILE_ALIAS_ IS '手机表单别名';

alter table bpm_sol_fv add MOBILE_NAME_ varchar(50);
COMMENT ON COLUMN bpm_sol_fv.MOBILE_NAME_ IS '手机表单名称';
